# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mail-service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12mail-service.proto\"<\n\x0fScheduleRequest\x12\x17\n\x0fnotification_id\x18\x01 \x01(\x05\x12\x10\n\x08\x64\x65\x61\x64line\x18\x02 \x01(\t\"&\n\x10ScheduleResponse\x12\x12\n\nadd_status\x18\x01 \x01(\x05\"2\n\x17NotificationInfoRequest\x12\x17\n\x0fnotification_id\x18\x01 \x01(\x05\"\xa1\x01\n\x18NotificationInfoResponse\x12\x17\n\x0fnotification_id\x18\x01 \x01(\x05\x12\x15\n\rproject_title\x18\x02 \x01(\t\x12\x15\n\rsection_title\x18\x03 \x01(\t\x12\x1a\n\x12notification_title\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\r\n\x05\x65mail\x18\x06 \x03(\t\"N\n!UpdateScheduleNotificationRequest\x12\x17\n\x0fnotification_id\x18\x01 \x01(\x05\x12\x10\n\x08\x64\x65\x61\x64line\x18\x02 \x01(\t\";\n\"UpdateScheduleNotificationResponse\x12\x15\n\rupdate_status\x18\x01 \x01(\x05\x32\xb4\x01\n\x0eMailingService\x12;\n\x14ScheduleNotification\x12\x10.ScheduleRequest\x1a\x11.ScheduleResponse\x12\x65\n\x1aUpdateScheduleNotification\x12\".UpdateScheduleNotificationRequest\x1a#.UpdateScheduleNotificationResponse2`\n\x0e\x42\x61\x63kendService\x12N\n\x17GetFullNotificationInfo\x12\x18.NotificationInfoRequest\x1a\x19.NotificationInfoResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mail_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCHEDULEREQUEST._serialized_start=22
  _SCHEDULEREQUEST._serialized_end=82
  _SCHEDULERESPONSE._serialized_start=84
  _SCHEDULERESPONSE._serialized_end=122
  _NOTIFICATIONINFOREQUEST._serialized_start=124
  _NOTIFICATIONINFOREQUEST._serialized_end=174
  _NOTIFICATIONINFORESPONSE._serialized_start=177
  _NOTIFICATIONINFORESPONSE._serialized_end=338
  _UPDATESCHEDULENOTIFICATIONREQUEST._serialized_start=340
  _UPDATESCHEDULENOTIFICATIONREQUEST._serialized_end=418
  _UPDATESCHEDULENOTIFICATIONRESPONSE._serialized_start=420
  _UPDATESCHEDULENOTIFICATIONRESPONSE._serialized_end=479
  _MAILINGSERVICE._serialized_start=482
  _MAILINGSERVICE._serialized_end=662
  _BACKENDSERVICE._serialized_start=664
  _BACKENDSERVICE._serialized_end=760
# @@protoc_insertion_point(module_scope)
